// Generated by CoffeeScript 1.6.3
(function() {
  var TodoItem, TodoList;

  TodoItem = (function() {
    function TodoItem(description, tags) {
      this.desc = description;
      this.tags = tags != null ? tags : [];
      this.isDone = false;
    }

    TodoItem.prototype.addTag = function(tagName) {
      if (tagName != null) {
        return this.tags.push(tagName);
      }
    };

    TodoItem.prototype.removeTag = function(tagName) {
      if ((tagName != null) && this.tags.indexOf(tagName) !== -1) {
        return this.tags.splice(this.tags.indexOf(tagName), 1);
      }
    };

    TodoItem.prototype.changeDesc = function(newDesc) {
      if (!!newDesc) {
        return this.desc = newDesc;
      }
    };

    TodoItem.prototype.markAsDone = function(toggle) {
      if ((toggle != null) && toggle === true) {
        return this.isDone = true;
      } else {
        return this.isDone = false;
      }
    };

    TodoItem.prototype.toHTML = function() {
      var tag, tagMarkup;
      tagMarkup = ((function() {
        var _i, _len, _ref, _results;
        _ref = this.tags;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          tag = _ref[_i];
          _results.push("<span class='tag'>" + tag + "</span>");
        }
        return _results;
      }).call(this)).join("");
      return "<li>" + this.desc + tagMarkup + "</li>";
    };

    return TodoItem;

  })();

  TodoList = (function() {
    function TodoList(category) {
      this.category = category;
      this.items = [];
    }

    TodoList.prototype.addItem = function(description) {
      if (description != null) {
        return this.items.push(new TodoItem(description, []));
      }
    };

    TodoList.prototype.removeItem = function(description) {
      if (description != null) {
        return this.items.forEach(function(item, i) {
          if (item.desc === description) {
            return this.items.splice(i, 1);
          }
        });
      }
    };

    return TodoList;

  })();

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
